# Generated by Django 6.1 on 2026-08-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tecnico', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='gestores/')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_cnat', models.IntegerField()),
                ('placar_adversario', models.IntegerField()),
                ('nome_adversario', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=100)),
                ('competicao', models.CharField(blank=True, choices=[('jerns', 'JERNS'), ('jebs', 'JEBS'), ('juverns', 'JUVERNS'), ('fnde', 'FNDE'), ('intercampi', 'Intercampi'), ('jifs', 'JIFs'), ('', 'JERNS')], max_length=100)),
                ('fase_competicao', models.CharField(max_length=100)),
                ('fase_jogo', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('marcado', 'Marcado'), ('finalizado', 'Finalizado')], default='marcado', max_length=50)),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Figurinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='figurinhas/')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to='core.esporte')),
            ],
        ),
        migrations.CreateModel(
            name='Seletiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('hora', models.CharField(max_length=50)),
                ('esporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seletiva', to='core.esporte')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fotos', models.ManyToManyField(blank=True, related_name='tags', to='core.foto')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=500)),
                ('conteudo', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='noticias', to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('local', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='core.tag')),
            ],
        ),
    ]
