# Generated by Django 6.1.1 on 2026-09-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='competicao',
            field=models.CharField(blank=True, choices=[('jerns', 'JERNS'), ('jebs', 'JEBS'), ('juverns', 'JUVERNS'), ('fnde', 'FNDE'), ('intercampi', 'Intercampi'), ('jifs', 'JIFs'), ('jerns', 'JERNS')], max_length=100),
        ),
    ]
