# Generated by Django 6.1.1 on 2026-09-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='fase_competicao',
            field=models.CharField(choices=[('polos', 'Polos'), ('estadual', 'Estadual'), ('nordeste', 'Nordeste'), ('nacional', 'Nacional')]),
        ),
    ]
