# Generated by Django 6.1 on 2026-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jogo_fase_competicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='fase_competicao',
            field=models.CharField(choices=[('polos', 'Polos'), ('estadual', 'Estadual'), ('nordeste', 'Nordeste'), ('nacional', 'Nacional')]),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='fase_jogo',
            field=models.CharField(choices=[('Fase_de_grupos', 'Fase de Grupos'), ('64_avos', '64 avos'), ('32_avos', '32 avos'), ('16_avos', '16 avos'), ('oitavas', 'Oitavas'), ('quartas', 'Quartas'), ('semi', 'Semi'), ('final', 'Final')]),
        ),
    ]
