# Generated by Django 6.1 on 2026-09-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_foto_fase_competicao_alter_jogo_fase_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.evento'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='competicao',
            field=models.CharField(blank=True, choices=[('jerns', 'JERNS'), ('jebs', 'JEBS'), ('juverns', 'JUVERNS'), ('fnde', 'FNDE'), ('intercampi', 'Intercampi'), ('jifs', 'JIFs'), ('jerns', 'JERNS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='edicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='esporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='core.esporte'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='fase_competicao',
            field=models.CharField(blank=True, choices=[('polos', 'Polos'), ('estadual', 'Estadual'), ('nordeste', 'Nordeste'), ('nacional', 'Nacional')], null=True),
        ),
    ]
